### ISSUE TITLE
安全にCIからdbtコマンドを実行し本番反映を自動化する仕組みの検討

### ISSUE THREAD

**Issue by yrarchi** [yrarchi/ga4_dbt_mart#19]
dbtモデルを CI（GitHub Actions）から定期的に自動実行・反映できるようにしたい。
ただし、Google Cloud 認証情報の取り扱いを極力安全に行いたい。

**Comment by yrarchi** [comment]
### 検討①: サービスアカウント鍵を secrets に登録する方法（base64化）

#### 方法概要

- GCP サービスアカウント鍵（JSON）を base64 でエンコード
- GitHub Secrets に登録
- CI 中で復元し、`GOOGLE_APPLICATION_CREDENTIALS` として利用
- `main` ブランチにpushした時のみ Workflow が実行されるよう制限する

#### 残る懸念点

* 秘密鍵は長期有効で漏洩リスクが高い
* ログ等への誤出力で漏れた場合、権限付きで使われ得る
* 鍵のローテーションが手動で煩雑

**Comment by yrarchi** [comment]
### 検討②: OIDC + Workload Identity Federation を使った認証

#### 方法概要

GitHub Actions では、OpenID Connect（OIDC）という仕組みを使って「**GitHub Actions であることを証明するトークン**」を GCP に送信できる。

これを利用して、GCP 側で設定した **Workload Identity Provider / Pool** を通じて、
秘密鍵なしで一時的にサービスアカウントを impersonate する（なりすまし） ことが可能。

 #### 用語

* **OIDC（OpenID Connect）**: GitHub が「自分は信頼されたワークフローです」と証明するための署名付きトークン（IDトークン）を発行するプロトコル
* **Workload Identity Pool**: GCP 外部の ID（ここでは GitHub）と GCP の IAM（サービスアカウント）を紐づける受け皿
* **Workload Identity Provider**: どの外部ID（GitHubリポジトリなど）を信頼するかを具体的に定義する構成要素。Pool内に複数作れる

#### 認証の流れ

1. GitHub Actions のジョブ内で、OIDC トークンを自動で発行
2. GCP 側の Workload Identity Provider がそのトークンの発行元（リポジトリ・ブランチなど）を検証
3. 条件を満たしていれば、一時的に指定したサービスアカウントの権限を付与
4. `gcloud` や `dbt` などがサービスアカウント権限で動作できる

#### 利用イメージ（GitHub Actions）
https://github.com/google-github-actions/auth

```yaml
- name: Authenticate to Google Cloud
  uses: google-github-actions/auth@v2
  with:
    workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
    service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
```

#### セキュリティ上の強み

* 秘密鍵不要：鍵ファイルの漏洩リスクが根本的に存在しない
* トークンは短命：1時間程度で自動失効。漏れても再利用不可
* 信頼元の制限：特定の GitHub リポジトリ／ブランチ／環境だけを信頼可能
* PR由来のWorkflowではトークンが発行されない**：意図しない実行経路からの認証を防止
* ローテーション不要：秘密鍵の更新・配布が不要で保守性が高い
